export const auth_token = 'eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktZXhhbXBsZSIsInN1YiI6ImFkbWluQG5lc3RvLmNvbSIsImF1ZCI6IndlYiIsImlhdCI6MTYxMDkxMjk2MywiZXhwIjoxNjEwOTE0NzYzfQ.nS-8c3xnwLV46kjET5hySlBSXLe53f0KnMSZNfglY0jUs-dqGEHi_cUqmDmsCoI3h6wiIpndKy9-vDchWKeJUQ';


